[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hije"
version = "0.1.0"
description = "A non-linear optimization approach to joint deconvolution"
authors = [
    { name = "Antoine Marchal", email = "antoine.marchal@anu.edu.au" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"

# leave out torch here
dependencies = [
    "numpy",
    "scipy",
    "astropy"
]

[project.optional-dependencies]
torch = ["torch"]
docs = ["sphinx", "furo"]

[project.urls]
Homepage = "https://github.com/antoinemarchal/hije"

[project.optional-dependencies]
docs = [
    "sphinx",
    "furo"
]