[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DECONV"
version = "0.1.0"
description = "A non-linear optimization approach to joint deconvolution"
authors = ["Antoine Marchal antoine.marchal@anu.edu.au"]
license = "GPL-3.0"
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "numpy",
    "scipy",
    "torch",
    "astropy"
]

[project.urls]
Homepage = "https://github.com/antoinemarchal/deconv"