[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deconv"
version = "0.1.0"
description = "A non-linear optimization approach to joint deconvolution"
authors = [
    { name = "Antoine Marchal", email = "antoine.marchal@anu.edu.au" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "numpy",
    "scipy",
    "torch",
    "astropy"
]

[project.urls]
Homepage = "https://github.com/antoinemarchal/deconv"